services:
  vespa:
    image: vespaengine/vespa:8.277.17
    container_name: vespa
    hostname: vespa-container
    ports:
      - "4080:4080"
      - "19071:19071"
    environment:
      - VESPA_CONFIGSERVER_JVMARGS=-Xms128m -Xmx512m
      - VESPA_CONFIGPROXY_JVMARGS=-Xms32m -Xmx128m
    networks:
      - search_network

networks:
  search_network:
    driver: bridge